### ISSUE TITLE
Performance testing

### ISSUE THREAD

**Issue by amilajack** [icodeforlove/task.js#1]
Would be nice if you could benchmark this module.

**Comment by icodeforlove** [comment]
Have a list of others I should be testing against?

**Comment by amilajack** [comment]
Benchmark as in run, say a fibonacci function, on one thread and then compare that to a  parallelize version of it using task.js.

**Comment by icodeforlove** [comment]
I'll do more tests later but for raw message passing in node.js its easily a magnitude faster.

**Comment by icodeforlove** [comment]
But please remember this is not the goal of something like this, i mean it doesnt hurt that its much faster with these things. But real world usage is really meant to be for chunking blocking work.

Also my main reason for making this was when I working with WebGL i noticed i needed to process some very large arrays (30M+). It was taking 4 seconds in my browser, and it came up with this. I only chunked work into 6 workers but it brought 4000ms down to 500ms, and when i introduced transferable buffers it went down to 250ms.
