### ISSUE TITLE
How to use on server side?

### ISSUE THREAD

**Issue by katopz** [icodeforlove/task.js#25]
I try
```js
var task = require('task');

function pow(number) {
    return Math.pow(number, 2);
}

var powTask = task.wrap(pow);
powTask(2).then(function (squaredNumber) {
    console.log(squaredNumber);
});
```
But get error
```
"task.wrap is not a function"
```

I also try
```js
import Task from 'task';

const task = new Task();

task.run({
    arguments: [2],
    function: (number) => {
        console.log('pow:', number);
        return Math.pow(number, 2);
    }
}).then(
    (result) => {
        console.log('done:', result);
    },
    (err) => {
        console.log('err:', err);
    }
);
```
But only `done: true` is print?

Any hint?

**Comment by icodeforlove** [comment]
its `task.js` not `task`

**Comment by katopz** [comment]
Awwww snap! sorry for wasting your time. 😭

**Comment by icodeforlove** [comment]
No problem, updated the docs to make it a little more clear. 

By the way we are both located in Bangkok.

**Comment by katopz** [comment]
Oh! cool, traveling? Do tweet me anytime if you're in trouble ;)

**Comment by icodeforlove** [comment]
Nope, living here for the past 3+ years :).

Seems like we are running close to the same tech stacks, may be useful for both of us to sync up one of these days. Not many node/docker/react... devs around here.

**Comment by katopz** [comment]
Yeah I getting hard time finding one too. Here's my stack atm https://github.com/otterhq/otter-stack.

Would you mind add my [fb](https://www.facebook.com/katopz) so we can chat there.
It's kinda off topic already and shame that we know each other because of my stupid lol.
