### ISSUE TITLE
How to use dependencies in my worker task?

### ISSUE THREAD

**Issue by vitorcremonez** [icodeforlove/task.js#31]
Importing another dependencies inside of a worker task is broking the code. I think that when is passed to Blob method, the webpack don't know, how to deal with imports and requires.

Error:
Can't find variable: __webpack_require__

**Comment by icodeforlove** [comment]
You are doing this on the frontend?

If so you may want to convert the module to a string, or as a global.

I have opened #33 up for server-side requirements.

**Comment by icodeforlove** [comment]
@vitorcremonez We now have a consistent interface for this on both the browser, and node (#41).

It involves just passing in a `requires` object into the Task.js initialization.
