### ISSUE TITLE
Async work?

### ISSUE THREAD

**Issue by icodeforlove** [icodeforlove/task.js#5]
This doesn't make sense for WebWorkers, but this may make sense for SharedWorkers.

**Comment by icodeforlove** [comment]
A work around for Node.js is

- https://www.npmjs.com/package/deasync

But the more i think about it maybe if the function you pass into Task.js returns a promise it just waits for a resolve, and sends the resolution back to the manager. Then we can easily support both situations.

**Comment by emptyflash** [comment]
This is a huge use case for me. It would allow you to take code that is already concurrent and make it parallel essentially for free.

**Comment by icodeforlove** [comment]
I added minimal support for this in 0.0.24

You can try it like this in a modern browser

```
let powTask = task.wrap(number => {
	return new Promise((resolve, reject) => {
		setTimeout(() => {
			resolve(Math.pow(number, 2));
		}, 4000);
	});
});

powTask(2).then((squaredNumber) => console.log(squaredNumber));
```

Promises are much easier to support than old callback style, but you can always wrap one of those into a promise.

**Comment by icodeforlove** [comment]
@emptyflash I know this is late but I did recently add the ability to also set `workerTaskConcurrency`.

```javascript
let powTask = task.wrap(async number => {
	let data = await globals.request.get('...');
	/* do something computationally heavy with the data*/
	return data;
});
```

By increasing workerTaskConcurrency, it would allow more inflight requests in this situation. Depending on your type of work this can be useful, and you can offload some of the networking load from your main process, as well as processing load.

**Comment by icodeforlove** [comment]
I have done a bad job at documenting this but you can use the initialize function to do your requires, bind all module includes and helper functions to the globals object inside of the workers.
